apiVersion: v2
name: physical-tracking-service
description: A Helm chart for Physical Tracking Service - real-time tracking of physical inventory movements and license plates
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - warehouse
  - tracking
  - inventory
  - license-plate
  - rtls
maintainers:
  - name: WES Team
    email: wes-team@paklog.com
home: https://physical-tracking.paklog.com
sources:
  - https://github.com/paklog/physical-tracking-service
