{{- if not .Values.secrets.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "physical-tracking-service.fullname" . }}-secrets
  labels:
    {{- include "physical-tracking-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.database.key }}: {{ .Values.secrets.database.password | b64enc | quote }}
  {{- if and .Values.secrets.apiKey.value (not .Values.secrets.apiKey.existingSecret) }}
  {{ .Values.secrets.apiKey.key }}: {{ .Values.secrets.apiKey.value | b64enc | quote }}
  {{- end }}
{{- end }}
