spring:
  application:
    name: physical-tracking-service

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/physical_tracking}
      database: physical_tracking

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: physical-tracking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  # Spring MVC Configuration
  mvc:
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      media-types:
        json: application/json

# Logging Configuration
logging:
  level:
    root: INFO
    com.paklog.wes.tracking: DEBUG
    org.springframework.kafka: WARN
    org.mongodb.driver: WARN

# Application-specific Configuration
tracking:
  license-plate:
    auto-generate: true
    format: LP-{timestamp}-{sequence}
  movement:
    audit-enabled: true

# CloudEvents Configuration
cloudevents:
  kafka:
    topic: wes-tracking-events
    source: /wes/physical-tracking-service

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: when-authorized
  health:
    mongo:
      enabled: true
    kafka:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: dev
      service-type: wes
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
